export ARCHS=armv7 arm64
include theos/makefiles/common.mk

BUNDLE_NAME = ProtectiPlusFlipSwitch
ProtectiPlusFlipSwitch_FILES = Switch.x
ProtectiPlusFlipSwitch_FRAMEWORKS = UIKit
ProtectiPlusFlipSwitch_LIBRARIES = flipswitch
ProtectiPlusFlipSwitch_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk
