export ARCHS=armv7 arm64

include theos/makefiles/common.mk

TWEAK_NAME = protectiplustoggleforactivator
protectiplustoggleforactivator_FILES = Tweak.xm
protectiplustoggleforactivator_LDFLAGS = -lactivator

include $(THEOS_MAKE_PATH)/tweak.mk
