export ARCHS=armv7 arm64

include theos/makefiles/common.mk

TWEAK_NAME = protectiplustoggleforquickdo
protectiplustoggleforquickdo_FILES = Action.m
protectiplustoggleforquickdo_LDFLAGS = -lquickdo

include $(THEOS_MAKE_PATH)/tweak.mk
